### ISSUE TITLE
ros2 topic list fails

### ISSUE THREAD

**Issue by mstiehm-NF** [micro-ROS/micro_ros_stm32cubemx_utils#96]
Hi all. I was able to get a custom lwip UDP transport working and my node is successfully publishing, but when i try to do a ros2 topic list, the command fails with:
```
Traceback (most recent call last):
  File "/opt/ros/humble/install/bin/ros2", line 33, in <module>
    sys.exit(load_entry_point('ros2cli==0.18.5', 'console_scripts', 'ros2')())
  File "/opt/ros/humble/install/lib/python3.8/site-packages/ros2cli/cli.py", line 89, in main
    rc = extension.main(parser=parser, args=args)
  File "/opt/ros/humble/install/lib/python3.8/site-packages/ros2topic/command/topic.py", line 41, in main
    return extension.main(args=args)
  File "/opt/ros/humble/install/lib/python3.8/site-packages/ros2topic/verb/list.py", line 56, in main
    topic_names_and_types = get_topic_names_and_types(
  File "/opt/ros/humble/install/lib/python3.8/site-packages/ros2topic/api/__init__.py", line 41, in get_topic_names_and_types
    topic_names_and_types = node.get_topic_names_and_types()
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1109, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1450, in __request
    response = self.__transport.request(
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1153, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1169, in single_request
    return self.parse_response(resp)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1341, in parse_response
    return u.close()
  File "/usr/lib/python3.8/xmlrpc/client.py", line 655, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault 1: "<class 'rclpy._rclpy_pybind11.RCLError'>:failed to get topic names and types: error not set">
```

I am using the standard Int32 publisher example.

**Comment by mstiehm-NF** [comment]
This ended up being that I sourced multiple ROS installs. all good now!

**Comment by DaniGarciaLopez** [comment]
Hi @mstiehm-NF,

Would you mind sharing your custom transport? I'm also interested on having UDP as the transport layer but have no experience with custom transports and lwip

**Comment by mstiehm-NF** [comment]
> Hi @mstiehm-NF,
> 
> Would you mind sharing your custom transport? I'm also interested on having UDP as the transport layer but have no experience with custom transports and lwip

Sure, no problem. Assuming you have UDP working on your board, this should work:
(I tried the netconn api, but decided not to use it but left it commented out)
```
#include "micro_ros_lwip_transport.h"
#include <trace_custom.h>

bool lwip_transport_open(
        uxrCustomTransport* transport)
{
	// struct netconn *conn;
	// conn = netconn_new(NETCONN_UDP);
	// transport->args = (void *)&conn;
	// err_t err;
	// ip_addr_t dest_ip;
	// if(ipaddr_aton("10.97.0.200", &dest_ip))
	// {
	// 	if (conn!= NULL)
	// 	{
	// 		err = netconn_connect(conn, &dest_ip, 7777);
	// 		if (err == ERR_OK)
	// 		{
	// 			return true;
	// 		}
	// 	}
	// }
	// return false;
	custom_transport_data_t * transport_data = (custom_transport_data_t*) transport->args;
	bool connected = false;
	while(!connected)
	{
		int status = lwip_connect(transport_data->socket, (struct sockaddr*)&transport_data->addr, sizeof(transport_data->addr));
		if (status != 0)
		{
			trace_line("Failed to connect to %d.%d.%d.%d:%d, code: %d",
				(transport_data->addr.sin_addr.s_addr      ) & 0xFF,
				(transport_data->addr.sin_addr.s_addr >>  8) & 0xFF,
				(transport_data->addr.sin_addr.s_addr >> 16) & 0xFF,
				(transport_data->addr.sin_addr.s_addr >> 24) & 0xFF,
				PP_NTOHS(transport_data->addr.sin_port),
				status);
		}
		else
		{
			trace_line("Connected to %d.%d.%d.%d:%d",
				(transport_data->addr.sin_addr.s_addr      ) & 0xFF,
				(transport_data->addr.sin_addr.s_addr >>  8) & 0xFF,
				(transport_data->addr.sin_addr.s_addr >> 16) & 0xFF,
				(transport_data->addr.sin_addr.s_addr >> 24) & 0xFF,
				PP_NTOHS(transport_data->addr.sin_port));
				connected = true;
		}
		osDelay(1000);
	}
	return connected;
}

bool lwip_transport_close(
        uxrCustomTransport* transport)
{
	// struct netconn *conn;
	// conn = (struct netconn *) transport->args;
	// err_t err = netconn_close(conn);
	// if( err == ERR_OK)
	// {
	// 	return true;
	// }
	// return false;
	custom_transport_data_t * transport_data = (custom_transport_data_t*) transport->args;
	lwip_close(transport_data->socket);
	return true;
}

size_t lwip_transport_write(
        uxrCustomTransport* transport,
        const uint8_t* buf,
        size_t len,
        uint8_t* errcode)
{
	// err_t err;
	// struct netconn *conn;
	// conn = (struct netconn *) transport->args;
	// err = netconn_write(conn, (const unsigned char*)(buf), len, NETCONN_NOCOPY);
	// if(err == ERR_OK)
	// {
	// 	errcode = 0;
	//     return len;
	// }
	// uint8_t errval = (err < 0) ? (uint8_t)-err : (uint8_t)err;
	// *errcode = errval;
	// return (size_t)-1;
	custom_transport_data_t * transport_data = (custom_transport_data_t*) transport->args;

	if (lwip_send(transport_data->socket, buf, len, 0) == -1)
	{
		trace_line("Lwip send ERROR");
		*errcode = 1;
		return 0;
	}
	*errcode = 0;
  return len;
}

size_t lwip_transport_read(
        uxrCustomTransport* transport,
        uint8_t* buf,
        size_t len,
        int timeout,
        uint8_t* errcode)
{
	// struct netconn *conn;
	// conn = (struct netconn *)transport->args;
	// netconn_set_recvtimeout(conn, timeout);
	// struct netbuf *inbuf;
	// err_t recv_err;
	// /* Read the data from the port, blocking if nothing yet there.
	// We assume the request (the part we care about) is in one netbuf */
	// recv_err = netconn_recv(conn, &inbuf);

	// if (recv_err == ERR_OK)
	// {
	// 	if (netconn_err(conn) == ERR_OK)
	// 	{
	// 		netbuf_data(inbuf, (void**)&buf, (u16_t *)&len);
	// 		errcode = 0;
	// 		netbuf_delete(inbuf);
	// 		return len;
	// 	}

	// }
	// netbuf_delete(inbuf);
	// uint8_t errval = (recv_err < 0) ? (uint8_t)-recv_err : (uint8_t)recv_err;
	// *errcode = errval;
	// return (size_t)-1;
	custom_transport_data_t * transport_data = (custom_transport_data_t*) transport->args;
	size_t result = 0;
	if (len == 0)
	{
		*errcode = 0;
		return 0;
	}
	// set the timeout for receiving data
	struct timeval time_out;
	time_out.tv_sec = timeout / 1000;
	time_out.tv_usec = (timeout % 1000) * 1000;
	if (setsockopt(transport_data->socket, SOL_SOCKET, SO_RCVTIMEO, &time_out, sizeof(time_out)) < 0) 
	{
		trace_line("setsockopt failed for socket %d", transport_data->socket);
	}
	result = lwip_recv(transport_data->socket, buf, len, 0);
	//if (result == 0)
	if ((int)result == -1)
	{
		//trace_line("Socket Error!");
		*errcode = 1;
		return 0;
	}
	*errcode = 0;
	return result;
}
```

You also need this defined in your h file
```
typedef struct {
	struct sockaddr_in addr;
	int socket;
} custom_transport_data_t;
```

**Comment by DaniGarciaLopez** [comment]
Thanks a lot for sharing the transport! This is going to be the perfect jumpstart for my project. You should consider dropping a PR with the UDP transport; I guess eProsima folks and the whole community will really appreciate the effort. Cheers!
